# version: "3.9"
services:

  mysql:
    image: mysql:8
    container_name: fittrack-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fittrack
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: fittrack-backend
    restart: always
    depends_on:
      mysql:
        condition: service_started
    environment:
      DB_URL: jdbc:mysql://mysql:3306/fittrack
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_TOKEN: ${JWT_SECRET}
      GEMINI_APIKEY: ${GEMINI_API_KEY}

  frontend:
    build: ./client
    container_name: fittrack-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data: